### ISSUE TITLE
Adding molecular orbitals example in docs failing

### ISSUE THREAD

**Issue by herbertludowieg** [exa-analytics/exatomic#224] opened 2021-05-26 17:51 UTC
**Describe the bug**
Examples on the documentation to add molecular orbitals to a universe are failing with `KeyError: 'Level shell not found'`

**To Reproduce**
I'm using the examples in the docs.
```
from exatomic.base import resource
from exatomic import gaussian, molcas, nwchem

# gaussian example
fni = gaussian.Fchk(resource('g09-ch3nh2-631g.fchk')).to_universe()
fni.add_molecular_orbitals(vector=range(10))

# molcas example
mol = molcas.Output(resource('mol-uo2-anomb.out'))
orb = molcas.Orb(resource('mol-uo2-anomb.scforb'))
# Just attach it to the universe
# mol.momatrix = orb.momatrix
# mol.orbital = orb.orbital

# Alternatively there's a convenience method on molcas.Output
mol.add_orb(resource('mol-uo2-anomb.scforb'))  # adds momatrix and orbital
uni = mol.to_universe()
uni.add_molecular_orbitals(vector=range(40, 60))

# nwchem example
nw = nwchem.Output(resource('nw-ch3nh2-631g.out')).to_universe()
nw.add_molecular_orbitals(vector=range(20))

```

**Additional context**
I'll try to go in and fix this when I have a chance to.

**Comment by tjduigna** [comment] 2021-11-03 00:11
Closing this as a duplicate of #204 as I believe the pandas version incompatibility is the underlying cause of this issue.

**Closed by tjduigna** 2021-11-03 00:11 UTC
