### ISSUE TITLE
Getting nan value in data

### ISSUE THREAD

**Issue by Ranjitmanna** [exa-analytics/exatomic#227] opened 2021-09-04 13:08 UTC
https://github.com/exa-analytics/exatomic/blob/8663224b5f8ee8797f8173e66591c6d6510aae56/exatomic/algorithms/delocalization.py#L252`
We are the beginner in `exatomic`. We have installed `exatomic 5.7`. For the analysis of optimal tuning, we have made two python script, using 1st one, we are generating the `gaussian `inputs from `exatomic `by putting particular alpha and gamma value and the 2nd one is for plotting. We are getting successfully `gaussian `input files from exatomic. After successful run of these input files using `gaussian 16`, while running the plotting script, we are getting the `j2 `value as `nan`. By debugging, we came to know that the problem may come from above referred line in `delocalization.py`. I am attaching a screenshot for your perusal. Could you please suggest me how to overcome this issue? 
Thank you 

![Screenshot from 2021-09-04 23-58-20](https://user-images.githubusercontent.com/90094463/132095324-66aeecad-a677-44ac-84c6-618f775c3c39.png)

**Comment by tjduigna** [comment] 2021-09-08 13:14
Hi, thanks for using exatomic and posting an issue! The error handling in this part of the code is pretty bad, but the first line of your screenshot showing
```
allylicH 0.10-0.10 not computed
```
suggests that either the extraction was not performed correctly (unlikely as I believe Gaussian 16 had been well supported) or there may be missing output files. Please confirm that the outputs ran to successful completion and have the required data.

For more context for your debugging: the error is actually likely in the `compute_curvature` method in `delocalization.py`. It is a bit convoluted due to the generality of the method.

**Comment by Ranjitmanna** [comment] 2021-09-10 17:06
Hi, thank you very much for your reply. For the tuning, we are taking the inputs generated from `exatomic` using different alpha and gamma value. What I have posted previously, that was for `p-nitroaniline` system. For the `benzene` molecule, when the gamma value is low the corresponding j2 values are computed successfully but with increasing gamma value, we are getting j2 value as nan. All the `gaussian` output files are showing successful completion. I am attaching the screenshot of the gamma, alpha and j2 value along with `gaussian` input and output files for the `benzene` molecule for your perusal. Am I doing something wrong? Could you please help me on this?
Thank you
![Screenshot](https://user-images.githubusercontent.com/90094463/132889972-243f6160-7fae-4492-8449-cd11a32a3457.png)
[input.zip](https://github.com/exa-analytics/exatomic/files/7144832/input.zip)
[output.zip](https://github.com/exa-analytics/exatomic/files/7144887/output.zip)

**Comment by tjduigna** [comment] 2021-09-15 01:50
It is likely an issue with the output files for those combinations of alpha and gamma that are showing as nans. The output parsing is working for many of the files so it is either that those output files are malformed somehow, or they differ substantially such that the parsing logic breaks. You can remove the try/except block around the `compute_curvature` function to see the cause of the failure and happy to accept a PR that includes a fix.

**Comment by tjduigna** [comment] 2021-11-03 00:23
Closing this as it is not likely a bug in the code. Feel free to re-open if you have more details.

**Closed by tjduigna** 2021-11-03 00:23 UTC
